export const SET_INITIAL_PROJECTS = 'SET_INITIAL_PROJECTS';
export const SET_PROJECT_FIELD = 'SET_PROJECT_FIELD';
export const ADD_TAG_TO_PROJECT = 'ADD_TAG_TO_PROJECT';
export const ADD_USER_TO_PROJECT = 'ADD_TAG_TO_PROJECT';
export const CREATE_PROJECT = 'CREATE_PROJECT';
